### ISSUE TITLE
 Error when running code

### ISSUE THREAD

**Issue by mooncakehub** [LiyaoTang/ERDA#2]
![0a4356b9f32d41d6e32b3f40ffbfaf7](https://github.com/LiyaoTang/ERDA/assets/138660085/a1cb6076-5c9a-4e93-ba09-3f7444b8e007)

thank you for your excellent work.However,when I run this code:
python main.py -c config/s3dis/randla_erda.yaml --gpus 2

Imet some error as you an see the picture

**Comment by mooncakehub** [comment]
and I try to run this code with a single gpu,I met the same Valueerror

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest.
From my side, it seems that your dataset is not properly loaded. Could you check if you have all the files in place and if there are processed / cached files?

You could specify `--debug` to have output on the terminal for better checking.

Best,
Liyao

**Comment by mooncakehub** [comment]
thank you for your reply ,I  have solved the error
