### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by LinLin1031** [LiyaoTang/ERDA#4]
Thanks for your wonderful work. I would like to know how to visualize the results after validation or test? @LiyaoTang

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest. But could you be more specific? For example, what would you want to visualize, and what type of visualization do you want to see? 

Best,
Liyao

**Comment by LinLin1031** [comment]
Thank you for your prompt reply, before this issue, I encountered the following problem: I can train and output the accuracy results normally when the mode is train. But when mode is val, running 'python main.py' gives the following error:
![image](https://github.com/LiyaoTang/ERDA/assets/50825626/18eab123-8949-4397-abbd-9a521d1f7c2e)
The beginning part of the error output above, and the end part of the error output below: @LiyaoTang 
![image](https://github.com/LiyaoTang/ERDA/assets/50825626/b9393b31-9815-4e2b-aceb-865e706a17d8)

**Comment by LiyaoTang** [comment]
Hi,

As indicated by the error messages, you are trying to use uninitialized values, which indicates that the checkpoint that you specify to load is different from the model that you specify to use. Please double-check if you are loading the correct checkpoint.

Best,
Liyao

**Comment by LinLin1031** [comment]
Thanks for the advice, I've fixed the problem. Back on topic, I would like to ask for advice on how to visualize the results of a validation or test. Because currently I can only get quantitative results like the below figure but not qualitative results. @LiyaoTang 

![image](https://github.com/LiyaoTang/ERDA/assets/50825626/eb4cc9ac-7f3c-41d9-acb5-d6d3464bba7c)

**Comment by LiyaoTang** [comment]
Hi,

Good to know that. Yes, we do not include the visualization code in the release, because it is coupled with several other projects and is hard to clean. However, we mostly adapt from the official RandLA-Net repo for visualization tools, so you could check out there if you want to do visualization.

Best,
Liyao

**Comment by LinLin1031** [comment]
I found some functions related to visualization in the [utils/tester.py](https://github.com/LiyaoTang/ERDA/blob/main/utils/tester.py) you provided. However I didn't find any place to call them. So can I just call them directly in main.py to visualize? @LiyaoTang

**Comment by LinLin1031** [comment]
> I found some functions related to visualization in the [utils/tester.py](https://github.com/LiyaoTang/ERDA/blob/main/utils/tester.py) you provided. However I didn't find any place to call them. So can I just call them directly in main.py to visualize? @LiyaoTang

I look forward to you answering my simple question at your convenience. Thank you very much! @LiyaoTang

**Comment by LiyaoTang** [comment]
Hi,

I do not think there is any visualization I wrote in the utils/tester.py, though there might be some leftover codes from KPConv / Closerlook3D.

But yes, you can certainly leverage those codes for your visualization purposes.

Best.
